services:
  - type: web
    name: inmo-backend
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PRODUCTION
        value: true
      - key: OPENROUTER_API_KEY
        sync: false
      - key: PROXYSCRAPE_API_KEY
        sync: false
